spec/graphql/mutations/remix_project_mutation_spec.rb, spec/lib/project_loader_spec.rb, spec/models/project_spec.rb, spec/rails_helper.rb
Fixes #192 
With the default setup some of the RSpec tests fail with
```
1) ProjectLoader when no project with identifier returns nil
Failure/Error: raise PhraseIdentifier::Error, 'Unable to generate a random phrase identifier' if phrase.blank?
PhraseIdentifier::Error:
Unable to generate a random phrase identifier
```
This is because the `words` database is empty.
An option `sample_words` is created for example groups that will create 10 sample words.
=> Ensure sample words exist for phrase generator

docker-compose.yml
Three changes here:
* import `POSTGRES_HOST` from the environment (`.env` file) rather than presetting it in docker-compose; this makes it easier to use another database without editing version-controlled files). This also brings editor-api into consistency with how projects-admin does it
* move postgres database exposed port to 5434, to avoid a clash with projects-admin
* add the shared development network so editor-api can see postgres/nginx in core-dev-services for those who choose to use it
=> Tweaks to allow using another database in local development

.env.example, config/application.rb, lib/corp_middleware.rb, spec/lib/corp_middleware_spec.rb
Intercepts active storage requests and adds the required headers needed to allow images to be utilised in the app.
=> Add middleware to intercept add CORP headers

app/models/user.rb
Currently `organisations` doesn't exist in profile so it's currently mocked. Slight tweak to future proof `organisation_ids` to ensure an array is returned
=> Fix user model organisation_ids array

config/environments/production.rb
We're seeing the following warning in deployments like [this one][1]:
You set your `config.assets.compile = true` in production.
This can negatively impact the performance of your application.
For more information can be found in this article:
https://devcenter.heroku.com/articles/rails-asset-pipeline#compile-set-to-true-in-production
Heroku is automatically running `rake assets:precompile` and `rake assets:clean` (which just removes old versions of assets) as part of the build step and the build will fail if either of these tasks fails. So we should be able to rely on precompiled assets being present and thus we should be able to set `config.assets.compile` in the Rails production environment.
[1]: https://dashboard.heroku.com/apps/editor-api-staging/activity/builds/f9360560-9d26-487b-825 …
=> Do not compile assets in production

db/schema.rb
In #267, this column was removed and then re-added. However, [the squashed merge commit][1] only included a single migration that did not add/remove the column was included, i.e. there was no net effect on `schools.reference`, but the `reference` column was still moved from near the top to near the bottom of the table in `schema.rb`.
Ideally `schema.rb` should reflect the state of the production database and so I've moved `reference` column back to where it was. This also means that other developers won't see unexpected differences in their `schema.rb` when they run the migrations locally.
[1]: https://github.com/RaspberryPiFoundation/editor-api/commit/f3248986273f62017a8d0bef58bdabc6282c6d78
=> Fix order of `schools.reference` in `schema.rb`

app/controllers/api/schools_controller.rb, lib/concepts/school/operations/create.rb, spec/concepts/school/create_spec.rb
Related to https://github.com/RaspberryPiFoundation/editor-standalone/issues/28
When a school is trying to be created, but validations fail, we now get this response:
```
{
"errors": {
"website":["can't be blank"],
"address_line_1":["can't be blank"],
"municipality":["can't be blank"],
"country_code":["can't be blank","is not included in the list"]
}
}
```
This is useful, as the FE application can now iterate on the keys, and selectively update each input field to show the error message.
Before this change we got:
```
{"error":"Error creating school: Website can't be blank,Address line 1 can't be blank,Municipality can't be blank,Country code can't be blank,Country code is not included in the list"}
```
which isn't useful, as we can't associate errors to fields
=> update school validations to return list of errors for frontend use

app/controllers/api_controller.rb
The check for `consider_all_requests_local` (true in development, false in test and production) meant that we were responding with a 500 for these 4 exceptions in development, and with 400, 404, 403 and 422 respectively in test and production. This made is tricky to develop clients of this API because they'd get different responses in development than they would in production.
The commits below have all touched this block of code but none of them explain why the behaviour is as it is, so I'm going to assume it's OK to change as I have here:
- 632f55d5
- c93169b9
- d597bd93
- 86414675
=> Consistently respond to errors in all environments

app/controllers/api/schools_controller.rb, app/models/school.rb, app/services/school_verification_service.rb, db/migrate/20240507162837_remove_organisation_id_from_schools.rb, db/schema.rb, lib/concepts/school/operations/create.rb, lib/profile_api_client.rb, spec/concepts/school/create_spec.rb, spec/features/school/creating_a_school_spec.rb, spec/services/school_verification_service_spec.rb, spec/support/profile_api_mock.rb
GitHub issue #273 
Following a discussion with @DanielBrierton, @sra405, @grega, @floehopper, @chrislo and me, we've agreed not to store Schools/Organisations in Profile for now. Editor API is going to be the canonical source of Schools in the short term and we'll only look to store them in Profile if a user need requires us to.
This change allows us to use Editor Standalone to create multiple Schools in this API, because we're no longer assigning the [same ID to every School created](https://github.com/RaspberryPiFoundation/editor-api/blob/6b5575e43dc3b4b689c319d0952eb9140db15418/lib/profile_api_client.rb#L19).
The individual commit notes describe the changes in more detail.
=> Editor API should be canonical source of Organisations

app/models/word.rb, db/migrate/20240514163045_drop_words.rb, db/schema.rb, db/seeds.rb, lib/phrase_identifier.rb, spec/factories/word.rb, spec/graphql/mutations/remix_project_mutation_spec.rb, spec/lib/phrase_identifier_spec.rb, spec/lib/project_loader_spec.rb, spec/models/filesystem_project_spec.rb, spec/models/project_spec.rb, spec/rails_helper.rb
There are less than 1000 rows in the file which means it really doesn't take long to load and parse, so I don't really see the point in storing them in the database. I've also cached them in memory, so that we don't reload them in every iteration of the `10.times` loop.
Previously the app didn't work unless we'd seeded the database which was an extra complication for developers and deployments. This change removes that complication.
My actual motivation for making the change is to make the deployment of a new instance of the app at test-editor-api.raspberrypi.org simpler.
=> Avoid caching words used in `PhraseIdentifier` in the database

app/models/user.rb, spec/factories/user.rb, spec/models/user_spec.rb
We don't need to go via the organisation -> roles mapping to check for the `editor-admin` role as we have access to the `roles` from Hydra directly.
=> Simplify `User#admin?`

.clabot
I got this wrong in PR #315. Sorry! It looks as though the username is actually ["dependabot[bot]"][1].
[1]: https://github.com/RaspberryPiFoundation/editor-api/commits?author=dependabot%5Bbot%5D
=> Fix dependabot username in .clabot contributors list

Gemfile.lock, db/migrate/20240612153258_create_good_job_settings.rb, db/migrate/20240612153259_create_index_good_jobs_jobs_on_priority_created_at_when_unfinished.rb, db/migrate/20240612153260_create_good_job_batches.rb, db/migrate/20240612153261_create_good_job_executions.rb, db/migrate/20240612153262_create_good_jobs_error_event.rb, db/migrate/20240612153263_recreate_good_job_cron_indexes_with_conditional.rb, db/migrate/20240612153264_create_good_job_labels.rb, db/migrate/20240612153265_create_good_job_labels_index.rb, db/migrate/20240612153266_remove_good_job_active_id_index.rb, db/migrate/20240612153267_create_index_good_job_jobs_for_candidate_lookup.rb, db/migrate/20240612153268_create_good_job_execution_error_backtrace.rb, db/migrate/20240612153269_create_good_job_process_lock_ids.rb, db/migrate/20240612153270_create_good_job_process_lock_indexes.rb, db/schema.rb
We were seeing the following error when attempting to enqueue emails using GoodJob
undefined method `broadcast' for ActiveSupport::Logger:Class (NoMethodError)
logger.extend(ActiveSupport::Logger.broadcast(each_logger))
It looks like this was likely fixed in v3.19.3[1] of GoodJob so we've decide to upgrade to the latest version.
After upgrading we ran
rails generate good_job:update
rails db:migrate
[1] https://github.com/bensheldon/good_job/blob/main/CHANGELOG.md#v3193-2023-09-28
=> Upgrade GoodJob gem

Gemfile, Gemfile.lock
I was seeing the following error when trying to write a test around the admin functionality in editor-api:
NoMethodError:
undefined method show_exceptions?' for #<ActionDispatch::Request POST
"http://www.example.com/amin/projects" for 127.0.0.1>
It looks as though this was [fixed in Sentry in PR 2049][1] and [released in version 5.10.0][2].
The sentry-rails version constraint was added in
8d2ca2adc62c91244511fe05f3b5d8e1341566b8 but there was no explanation for it so I've assumed it's not necessary.
[1]: https://github.com/getsentry/sentry-ruby/pull/2049
[2]: https://github.com/getsentry/sentry-ruby/blob/master/CHANGELOG.md#5100
=> Upgrade sentry-rails Gem

lib/hydra_public_api_client.rb, spec/models/user_spec.rb
Previously, when an API request was made using an expired or invalid access token, a `Faraday::UnauthorizedError` was raised and the request failed.
Recently we've seen a bunch of [these exceptions][3] happening due to some other problems in editor-standalone and/or in the editor-ui web component - see [this issue][1] for more details.
Failing hard with an exception like this seems a bit over the top when the user is trying to view a public project for which they don't need to be logged-in. And it seems as if `User.from_token` might have been [expecting][2] `HydraPublicApiClient.fetch_oauth_user` to return `nil` when the token was invalid when in fact it returns a `401 Unauthorized` HTTP status code which results in a `Faraday::UnauthorizedError` exception being raised.
This commit …
=> Make `User.from_token` robust to invalid token

Dockerfile, app/controllers/admin/projects_controller.rb
Installing libvips in the Docker container and replacing `ActiveStorage::Current.host=` with `ActiveStorage::Current.url_options=` means that /admin/projects renders without errors and the images can be displayed.
=> Fix projects admin

app/controllers/admin/schools_controller.rb, app/dashboards/school_dashboard.rb
Adds `created_at` field to the schools admin panel index / listing view, and sets the default order to `created_at` and `desc`.
This is to make it easier for folk verifying schools to handle the process more easily by more clearly seeing new schools which have been created and require verification.
The listing can still be ordered by any other field if needed (eg. name).
=> Admin: Add created_at to school index record and set default ordering

app/controllers/admin/schools_controller.rb, app/models/school.rb, app/models/teacher_invitation.rb, app/services/school_verification_service.rb, app/views/admin/schools/show.html.erb, config/routes.rb, lib/concepts/school_owner/invite.rb, lib/concepts/school_student/create.rb, lib/concepts/school_student/create_batch.rb, lib/tasks/classroom_management_helper.rb, spec/concepts/school_owner/invite_spec.rb, spec/concepts/school_student/create_batch_spec.rb, spec/concepts/school_student/create_spec.rb, spec/concepts/school_teacher/invite_spec.rb, spec/features/admin/schools_spec.rb, spec/features/school_owner/inviting_a_school_owner_spec.rb, spec/features/school_student/creating_a_batch_of_school_students_spec.rb, spec/features/school_student/creating_a_school_student_spec.rb, spec/features/school_teacher/inviting_a_school_teacher_spec.rb, spec/models/school_spec.rb, spec/models/teacher_invitation_spec.rb, spec/services/school_verification_service_spec.rb
This is mostly a refactoring PR in preparation for creating a school in Profile API upon verification in Editor API. Once we're creating schools in Profile API we'll need to keep them in sync with the data in Editor API. To make that easier this PR restricts a verified school from being rejected so that we don't have to handle updating/deleting schools in Profile API (at least for now).
This PR also:
- tightens up validation so that a school can only have one of `verified_at` or `rejected_at` set at a time, and so that once set those values can't be changed.
- adds tests around verification and rejection of schools in the admin UI before then simplifying those controller actions.
- fixes a bug in `SchoolVerificationService#verify` whereby a failed verification would appear to have been …
=> Prepare for generating school codes

app/controllers/api/teacher_invitations_controller.rb, spec/features/teacher_invitations/accepting_an_invitation_spec.rb
- Related to:
- #336
- #RaspberryPiFoundation/editor-standalone#181
- the [Invite teachers](https://github.com/orgs/RaspberryPiFoundation/projects/51/views/11?pane=issue&itemId=67112446) epic
- Security: This shouldn't have any impact on security
- Performance: This shouldn't have any impact on performance
This was unnecessarily strict which made testing in development a bit harder than it needed to be.
Previously we were always trying to create a new teacher role in the school and responding with a 422 Unprocessalbe entity (with a validation error) if the user already had that role. Now we respond with 200 OK and leave the existing role in place. We also set `TeacherInvitation#accepted_at` if it hasn't already been set.
None.
=> Allow teacher invitation to be accepted multiple times

.env.example, app/controllers/admin/schools_controller.rb, app/models/school.rb, app/models/user.rb, app/services/school_verification_service.rb, db/migrate/20240617104323_add_school_code.rb, db/schema.rb, lib/profile_api_client.rb, lib/school_code_generator.rb, lib/tasks/classroom_management_helper.rb, spec/factories/school.rb, spec/features/admin/schools_spec.rb, spec/lib/profile_api_client_spec.rb, spec/lib/school_code_generator_spec.rb, spec/models/school_spec.rb, spec/models/user_spec.rb, spec/services/school_verification_service_spec.rb
This PR expands `SchoolVerificationService#verify` so that it uses the Profile API to create the school in Profile during verification. If any part of verification fails (updating the school, creating the teacher and owner roles, or creating the school in Profile API) then we abort verification and display a message saying that verification failed.
=> Create schools in Profile API upon verification

app/views/invitation_mailer/invite_teacher.text.erb
Replacing "create coding lessons for students" with "create coding projects for students" as per the copy review with Max and Mel.
=> Fix copy in teacher invitation email

.circleci/config.yml, .env.example, app/models/teacher_invitation.rb, config/initializers/encryption.rb, spec/models/teacher_invitation_spec.rb
Related to: https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/159
This PR ensures that the `email_address` field on the `teacher_invitations` table is encrypted. We can't currently avoid storing this PII in the editor-api database (as we need to use the email adress to send the invitation email) but this change helps mitigate the risk of someone getting access to the production database. 
We haven't sent any teacher invitation emails in production yet, so we don't need to worry about migrating or encrypting any existing data. 
We need to set the following ENV variables on non-local environments: 
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
Rails provides a command, `bin/rails …
=> Encrypt teacher invitation email address

app/controllers/api/school_students_controller.rb, app/services/school_verification_service.rb, lib/concepts/school_student/create.rb, lib/concepts/school_student/create_batch.rb, lib/profile_api_client.rb, spec/concepts/school_student/create_batch_spec.rb, spec/concepts/school_student/create_spec.rb, spec/features/school_student/creating_a_batch_of_school_students_spec.rb, spec/features/school_student/creating_a_school_student_spec.rb, spec/features/school_student/deleting_a_school_student_spec.rb, spec/features/school_student/listing_school_students_spec.rb, spec/features/school_student/updating_a_school_student_spec.rb, spec/lib/profile_api_client_spec.rb, spec/services/school_verification_service_spec.rb, spec/support/profile_api_mock.rb
With this PR we're now creating students in Profile API when they're added in editor-standalone. There are a number of commits but they should all be fairly easy to follow in isolation:
- The first 5 commits refactor the `ProfileApiClient` in preparation for implementing `.create_school_student`.
- The next 3 commits add methods to `ProfileApiClient` to list, create and destroy safeguarding flags in Profile API.
- The penultimate commit adds a `before_filter` to  `SchoolStudentsController` that creates the relevant (teacher and/or owner) safeguarding flags in Profile API for the authenticated user.
- The final commit modifies `.create_school_student` so that it creates a student in Profile API.
Although the create student endpoint in Profile API allows us to create multiple students in a …
=> Create students in Profile API

.env.example
The POSTMARK_API_TOKEN variable introduced in 4ab58c49c494 doesn't need to be set in development, but it is useful to document how to set it if we want to use Postmark in development (e.g. when developing/testing HTML emails).
=> Add POSTMARK_API_TOKEN to .env.example

.clabot
Removes Tessy (no longer at RPF), adds [lpmi-13](https://github.com/lpmi-13) (who has signed the CLA).
=> Update cla-bot contributors

app/controllers/api/class_members_controller.rb, app/views/api/class_members/index.json.jbuilder, lib/concepts/school_student/list.rb, spec/concepts/school_student/list_spec.rb, spec/factories/user.rb, spec/features/class_member/listing_class_members_spec.rb, spec/features/school_student/listing_school_students_spec.rb, spec/support/profile_api_mock.rb
Updated class members controller to utilise `SchoolStudents:List` and return the student details in a nested `student` attribute in the class members response.
Previous Profile API mocks were for a single student so I expanded this to allow and test for a filtered subset using the `student_ids` array
=> List class member students

app/models/school.rb, spec/models/school_spec.rb
**Context**
UK postcode data is used in our reporting tools in order to measure how effective we are at reaching deprived areas (using the IMD / Indices of Multiple Deprivation: https://www.gov.uk/government/collections/english-indices-of-deprivation). This is a key part our programme impact monitoring work.
The IMD lookup relies on a correctly formatted postcode as defined by the NSPL (National Statistics Postcode Lookup) [data](https://geoportal.statistics.gov.uk/datasets/9ac0331178b0435e839f62f41cc61c16): 2-4 char outward code, a space, then a 3-char inward code.
**Problem**
Postcode validation (as in "is this an actual UK postcode that is definitely in the Royal Mail Postcode Address File / PAF") is suboptimal, as doing so with a regex is a pain and potentially error prone (with the …
=> Format UK school postcodes

app/views/api/lessons/index.json.jbuilder, app/views/api/my_school/show.json.jbuilder, spec/features/lesson/listing_lessons_spec.rb, spec/features/my_school/showing_my_school_spec.rb
- `code` has been added to the school show response for the dashboard
- `project` has been added to the lesson index so we can direct students to the project from the class page
=> Add properties to existing responses

.devcontainer/devcontainer.json, .env.example, config/environments/development.rb, docker-compose.yml, lib/hydra_public_api_client.rb
- Ready for review
- Use a different env var locally for the profile api, to allow simultaneous use of administrate and the api (at long last)
- This is a local only env var since staging and prod share the same url
- Remove network from docker-compose for now, as unused
- Add extensions to devcontainer.json
- Fix smee architecture to amd64
=> Fix_env_variables_to_allow_both_api_and_dashboard

.env.example, README.md, config/initializers/cors.rb, lib/corp_middleware.rb, lib/origin_parser.rb, lib/tasks/classroom_management_helper.rb, spec/lib/corp_middleware_spec.rb, spec/lib/origin_parser_spec.rb
- Closes https://github.com/RaspberryPiFoundation/editor-api/issues/405
This extends the current origin-setting functionality (literal origins set via a comma-separated environment variable) and allows the env var string to also contain regular expressions. These allow the origins to match dynamic patterns (eg. `https://*.projects-ui.pages.dev`) and ensures that configuration still remains in the environment as we don't want to assume that anyone running this application will want the same allowed origins configured as us (other than for `localhost` for local and test environments only).
eg. instead of currently having to set the following in `ALLOWED_ORIGINS`:
```
https://foo.raspberrypi.org, https://bar.raspberrypi.org, https://foo.editor-standalone-eyq.pages.dev, …
```
=> Allow for dynamic hosts in CORS origin config

app/controllers/api/projects_controller.rb, app/models/ability.rb, app/views/api/lessons/index.json.jbuilder, app/views/api/projects/show.json.jbuilder, config/routes.rb, db/migrate/20240902151414_add_finished_to_projects.rb, db/schema.rb, lib/concepts/project/operations/toggle_finished.rb, spec/models/ability_spec.rb, spec/requests/projects/show_spec.rb, spec/requests/projects/toggle_finished_spec.rb
- Closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/232
- Adds a boolean `finished` to projects
- Adds a new endpoint  `/api/projects/front-chow-empty/toggle_finished` that toggles `finished`
- Restricted to students, on a remix of one of their projects only
- Returns the flag on a standard show, if the project is a remix associated with a school
- Run `db:migrate`
=> 232: Add mark as finished endpoint

app/models/school.rb, spec/models/school_spec.rb
=> Update regex to allow longer and multi-part TLDs

lib/tasks/seeds_helper.rb, lib/tasks/test_seeds.rake
=> Increasing test seeds predictability

app/controllers/api/school_classes_controller.rb, spec/features/school_class/listing_school_classes_spec.rb
- Only return the classes for which the user is the teacher if `my_classes` query param is set
=> Add my classes filter to classes index endpoint

Gemfile.lock, app/controllers/api/projects/remixes_controller.rb, app/controllers/api/projects_controller.rb
- Related to https://github.com/RaspberryPiFoundation/editor-ui/issues/843
Fixes a bad request when no remix_origin is defined, this was leading to cypress integration tests failing.
N/A
=> 843: Ensure a fallback for a missing remix origin (mainly for cypress test failures)

app/models/project.rb, spec/concepts/project/update_spec.rb, spec/factories/project.rb, spec/requests/projects/show_spec.rb, spec/requests/projects/update_spec.rb
- Added extra validation to the `project` model to stop instructions being added to non-school projects
closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/393
=> Restrict instructions to school projects

lib/concepts/project/operations/create_remix.rb, spec/concepts/project/create_remix_spec.rb
closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/386
- Remixes copy audio and video files as well as images
=> Copy all media when project remixed

Dockerfile
This is required to build the psych Gem. Prior to this commit, running `docker compose build` would fail with:
```
65.20 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
65.20
65.20     current directory: /usr/local/bundle/gems/psych-5.1.2/ext/psych
65.20 /usr/local/bin/ruby extconf.rb
65.20 checking for yaml.h... no
65.20 yaml.h not found
65.20 *** extconf.rb failed ***
```
I don't understand why I'm seeing this error now because there don't appear to be any changes in the Dockerfile or docker-compose.yml files that could've caused it.
=> Add libyaml-dev to Dockerfile

docker-compose.yml
This should ensure that we can use host.docker.internal to connect to the host machine from within a container irrespective of the OS on the host machine.
The `host.docker.internal` address is [automatically available to Docker Desktop][1] on Windows and Mac, but [not on Linux without this additional configuration][2].
[1]: https://docs.docker.com/desktop/features/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
[2]: https://github.com/docker/for-linux/issues/264#issuecomment-964620100
=> Add host.docker.internal to docker-compose.yml

lib/project_importer.rb
- Closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/438
In some scenarios the blob is not being created properly on attach, which is causing a foreign key constraint, this change explicitly creates the blob prior to attaching it.
- Try re-running one of the failed jobs
=> Fix for attaching media in editor builds

app/controllers/api/school_owners_controller.rb, app/views/api/school_members/index.json.jbuilder, app/views/api/school_owners/_school_owner.json.jbuilder, app/views/api/school_owners/index.json.jbuilder, app/views/api/school_students/_school_student.json.jbuilder, lib/concepts/school_member/list.rb, lib/concepts/school_owner/list.rb, spec/concepts/school_member/list_spec.rb, spec/concepts/school_owner/list_spec.rb, spec/features/school_member/listing_school_members_spec.rb
- Related to https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/447
- Adds owners to the shool member list endpoint
- Adds a type to identify each user type
N/A
=> 447: Add owners and a type to school member list

app/controllers/api/class_members_controller.rb, app/views/api/class_members/index.json.jbuilder
closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/485
- Class teachers that are also a school owner are not returned in the format `owner: {class_member}` rather than `teacher: {class_member}` when listing class members. This allows the owner icon to be displayed next to them on the frontend.
=> Distinguish owners in class members list

.rubocop.yml, app/controllers/api/default_projects_controller.rb, app/controllers/api/projects_controller.rb, app/models/filesystem_project.rb, app/models/project.rb, lib/project_loader.rb, lib/tasks/seeds_helper.rb, spec/concepts/lesson/create_spec.rb, spec/concepts/project/create_spec.rb, spec/factories/project.rb, spec/features/lesson/creating_a_lesson_spec.rb, spec/graphql/mutations/create_project_mutation_spec.rb, spec/graphql/mutations/update_project_mutation_spec.rb, spec/jobs/upload_job_spec.rb, spec/lib/project_importer_spec.rb, spec/models/project_spec.rb, spec/requests/projects/show_spec.rb
This introduces the concept of projects of type "scratch" which we're going to need for the [Experience CS project](https://github.com/RaspberryPiFoundation/experience-cs). However, it goes to some pains to ensure that any existing clients of the API  (e.g. `editor-standalone`, `editor-ui`, the admin dashboard in `editor-api`, etc) will not see a scratch project for now unless they specifically choose to by adding a `project_type=scratch` query string parameter.
* [Add default scope to hide scratch projects](https://github.com/RaspberryPiFoundation/editor-api/pull/513/commits/bdf8cccf0c9c024aab81f469870802cbab6a8237)
* [Add scratch-only option for project show endpoint](https://github.com/RaspberryPiFoundation/editor-api/pull/513/commits/91e8466a8be86764b23c72024ceeac559e4fd642)
* …
=> Add support for Scratch projects

lib/tasks/project_components/experience_cs_example/project_config.yml
Do not merge until #513 has been merged and deployed. This will ensure that existing clients of the API are unable to "see" this example Scratch project.
This adds a simple example project of type "scratch". For the moment we're only planning to store metadata for Scratch projects in the `editor-api` database, so no components are included.
The seed data in production-like environments will need to be updated so this new project is added.
=> Add example Scratch project for Experience CS 

lib/tasks/project_components/experience_cs_example/project_config.yml
This reverts commit 4d4a1234d94421febea21d834e3d252175d46f2f.
The `ProjectImporter` doesn't currently play nicely with the `default_scope` we've added to `Project`. It correctly created the experience-cs-example project the first time the `rake projects:create_all` task ran on the deployment to staging but it fails on subsequent invocations because the `default_scope` prevents the importer from finding the existing Scratch project and it therefore attempts to create it again, resulting in:
> ActiveRecord::RecordInvalid: Validation failed: Identifier has already been taken (ActiveRecord::RecordInvalid)
=> Revert "Add example Scratch project for Experience CS"

Procfile
Ready for review
Removes projects:create_all from release process, which could be resetting default projects
N/A
=> Remove projects:create_all from release

Procfile, lib/tasks/projects.rake
This new rake task creates a single example project for the Experience CS app. If the project with the same `identifier` & `locale` already exists, the task is a no-op, i.e. the task is idempotent and can be safely run multiple times.
We look for the project based on just the `identifier` & `locale`, because there is validation and a database constraint that requires the combination of these two attributes to be unique. Thus if we don't find a project, we should be able to create one without an exception being raised.
We've used a separate rake task rather than incorporating it into the existing `projects:create_all` rake task for now, because there's some uncertainty about how that decides whether to overwrite a project. By keeping it completely separate we avoid iterating over all the …
=> Add projects:create_experience_cs_example rake task & run as part of Heroku release

app/controllers/api/projects/remixes_controller.rb, app/controllers/api/projects_controller.rb, app/controllers/api_controller.rb, app/controllers/concerns/project_scoping.rb, app/models/current.rb, app/models/project.rb, lib/project_loader.rb, spec/models/project_spec.rb, spec/requests/projects/remix_spec.rb
This extends the `project_type` param mechanism introduced in https://github.com/RaspberryPiFoundation/editor-api/pull/513 [into the `Api::Projects::RemixesController`](https://github.com/RaspberryPiFoundation/editor-api/commit/58875819cfebbfbd0f3a999271d78ae7544e1f3d) so that [the `experience-cs` app][1] can create a remix of a Scratch project and then show the remix. See [this pull request][2] for more details.
It also includes some preparatory refactoring [to extract a `Project.only_scratch` scope](https://github.com/RaspberryPiFoundation/editor-api/commit/00304473f251caca176e0de0977b9467ed4cf381) to reduce duplication. And then some subsequent refactoring [to extract a `ProjectScoping` controller concern and `Current.project_scope`](https://github.com/RaspberryPiFoundation/editor-api/c …
=> Create and show remixes for scratch projects

lib/tasks/projects.rake
See https://github.com/RaspberryPiFoundation/experience-cs/issues/451 & https://github.com/RaspberryPiFoundation/experience-cs/issues/454.
This renames a bunch of the seed Scratch projects used in Experience CS. See individual commit notes for details.
=> Experience CS: Update name of ten-block-mission project and consistently use sentence case for project names

app/controllers/api/schools_controller.rb, app/models/school.rb, app/views/api/my_school/show.json.jbuilder, app/views/api/school_owners/_school_owner.json.jbuilder, app/views/api/schools/_school.json.jbuilder, app/views/api/schools/index.json.jbuilder, app/views/api/schools/show.json.jbuilder, db/migrate/20250515081023_add_connected_apps_table.rb, db/migrate/20250515081023_add_user_origin_field_to_schools.rb, db/schema.rb, spec/features/school/creating_a_school_spec.rb, spec/models/school_spec.rb
- Closes https://github.com/RaspberryPiFoundation/editor-api/issues/543
- Security
- Performance
- Adds `user_origin` enum to capture user origin
- Adds a school template to make views more DRY
N/A
=> Add flag to identify school as linked to excs

app/views/api/lessons/index.json.jbuilder, app/views/api/projects/context.json.jbuilder, spec/requests/projects/show_context_spec.rb
Related to https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/648 and #558 
- Added project type to the project context route to support redirecting away from Scratch projects on the frontend
- Removed project finished data from the lessons index (which appears not to have been used and was throwing errors)
=> Adding `project_type` to project context

config/environments/test.rb, spec/concepts/school_student/create_batch_spec.rb, spec/jobs/create_students_job_spec.rb
TL;DR This makes the behaviour of ActiveJob in specs much more consistent and in doing so **fixes a long-lived flakey spec**.
Previously, the majority of the specs were using [the `GoodJob::Adapter`][1] in specs instead of [the built-in `ActiveJob::TestHelper::TestQueueAdapter`][2].
This was because of [the `config.active_job.queue_adapter = :good_job` line in `config/application.rb`][3] which was not overridden in [`config/environments/test.rb`][4].
However, confusingly, the `GoodJob::Adapter` has [an `execution_mode`][5] which [defaults to `inline` in the Rails test environment][6]. This means that by default, jobs will be executed inline, i.e. synchronously.
Adding to the confusion, the `SchoolStudent::CreateBatch` spec had [a `before` block which set the adapter to `:test`][7], i.e. …
=> Default to ActiveJob's test queue adapter in specs

app/views/admin/schools/show.html.erb, spec/features/admin/schools_spec.rb
Our customer success team want to know which School District a school in the US belongs to. At the moment we do not collect this information during registration so the team have to spend time working this out from the School's website and other information.
The Institute of Education Sciences maintains a website with data about all public schools in the US, including their School District.
This commit adds a link to the bottom of the school show page in the administrate dashboard to take the user to the search page on `https://nces.ed.gov`/ for the school's ZIP code.
I've shown a rough version of this feature to the team who will use it and they think it will be very useful until we start collecting this data at source.
The commit note has some additional context.
=> Add a link to the NCES search page for a school from its adminstrate dashboard

app/controllers/api/class_members_controller.rb, app/models/class_student.rb, app/models/class_teacher.rb, spec/features/class_member/creating_a_batch_of_class_members_spec.rb
So that it treats the request as successful even if some (or any) of the members couldn't be added to the class. Previously if _any_ member couldn't be added (likely due to them already being in the class) then the response code was 422 and the response only contained information about the errors and nothing about the members that were succesfully added.
In order to [use this `#create_batch` endpoint in Editor Standalone][1] we need to differentiate between a request that was processed successfully (irrespective of how many members were added to the class) and a request that couldn't be processed (e.g. because none of the supplied members exist in Profile API).
We've modified the return value from `#create_batch` such that it contains enough information to differentiate between the …
=> Change the response format for `ClassMembersController#create_batch`
