RaspberryPiFoundation/editor-api

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/test.rb
- spec/rails_helper.rb
closes #194
Status: Ready for review
Description: 
- Adds bullet gem to dev and test envs
- Add scout apm gem
> 194: Add bullet and scout

- .env.example
editor-ui has moved to port 3010
Also add editor.rpfdev.com for future use
> Update ALLOWED_ORIGINS for new editor-ui port

- Dockerfile
- README.md
- bin/db-sync/download-s3.sh
- bin/db-sync/load-local-db.sh
- bin/db-sync/production-to-local.sh
- bin/db-sync/staging-to-local.sh
Added our generic db-sync scripts with the tweaks needed to pull from the right heroku app
> Sync from prod or staging locally

- .env.example
- app/controllers/api/schools_controller.rb
- app/models/school.rb
- app/views/api/schools/index.json.jbuilder
- app/views/api/schools/show.json.jbuilder
- db/migrate/20240419102922_change_school_fields.rb
- db/migrate/20240419151721_add_index_to_schools.rb
- db/schema.rb
- docker-compose.yml
- lib/concepts/school/operations/create.rb
- spec/concepts/school/create_spec.rb
- spec/factories/school.rb
- spec/features/school/creating_a_school_spec.rb
- spec/models/school_spec.rb
Ready for review
Adds missing fields and tweaks model validations
> Update school fields

- .clabot
So that we can merge PRs from Dependabot.
> Add dependabot to clabot

- lib/tasks/classroom_management_helper.rb
Improve names, and remove special char
> Improve names, and remove special char

- README.md
> Adds brief testing docs to README

- README.md
- bin/docker-debug-entrypoint.sh
- bin/docker-entrypoint.sh
- lib/tasks/classroom_management_helper.rb
Ready for review
- Run seeds on container start
- Default lesson to 'students' visibility
- Update README
> Run seeds on container start, default lesson to 'students' visibility

- lib/tasks/classroom_management_helper.rb
Ready for review
- Creates a valid project in CEfE seed data
Recreate seed data:
`docker compose run --rm api rails classroom_management:destroy_seed_data`
`docker compose run --rm api rails classroom_management:seed_a_school_with_lessons_and_students`
> Fix the project seed data

- app/controllers/api/projects/remixes_controller.rb
- app/models/project.rb
- app/views/api/projects/remixes/index.json.jbuilder
- config/routes.rb
- spec/models/project_spec.rb
- spec/requests/projects/remix_spec.rb
> Add remixes endpoint

- app/jobs/upload_job.rb
- Ready for review
Prevents an error being raised if the github api query returns a NOT_FOUND error for the repo, since this can happen as a result of a race condition when the repo is first created.
> Don't raise an error if graphql finds a missing repo

- README.md
- db/seeds.rb
- lib/tasks/classroom_management.rake
- lib/tasks/seeds_helper.rb
- lib/tasks/test_seeds.rake
- spec/lib/classroom_management_spec.rb
- spec/lib/test_seeds_spec.rb
> Seed test data

- app/models/project.rb
> Filter out duplicate student ids when loading work

- lib/concepts/school_student/update.rb
- Ready for review
- Only try and decrypt the password if a password is passed, since resetting and updating student details use the same endpoint 
N/A
> Don't try and encrypt password if none passed

- app/models/school_class.rb
- spec/models/school_class_spec.rb
Closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/340
* Adds auditing for School Class
> adds auditing for school class

- app/controllers/api/school_students_controller.rb
- app/controllers/api/user_jobs_controller.rb
- app/views/api/school_students/create_batch.json.jbuilder
- lib/concepts/school_student/create_batch.rb
- Related to https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/322
- Improve handling where no jobs are found
N/A
> 322: Nicer handling for no jobs

- app/controllers/api/school_students_controller.rb
- lib/concepts/school_student/create_batch.rb
- spec/features/school_student/creating_a_batch_of_school_students_spec.rb
- Related to https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/320
- Security
- Performance
Adds error types to bulk student endpoint
N/A
> 320: Add error types

- lib/concepts/lesson/operations/create_copy.rb
- spec/concepts/lesson/create_copy_spec.rb
- spec/factories/lesson.rb
> Include project when lesson is copied

- app/controllers/api/projects_controller.rb
- app/views/api/projects/show.json.jbuilder
- config/locales/en.yml
- db/migrate/20250109140005_add_instructions_field_to_projects.rb
- db/schema.rb
- lib/concepts/project/operations/update.rb
- spec/concepts/project/update_default_component_spec.rb
- spec/concepts/project/update_delete_components_spec.rb
- spec/concepts/project/update_invalid_spec.rb
- spec/concepts/project/update_spec.rb
- spec/factories/project.rb
- spec/requests/projects/show_spec.rb
- spec/requests/projects/update_spec.rb
Closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/358
- Added `instructions` field to `Project` model
- Added condition to stop students updating project instructions
> Add instructions field

- .clabot
> Add Jamie Benstead to `.clabot`

- app/jobs/upload_job.rb
- app/models/filesystem_project.rb
- spec/jobs/upload_job_spec.rb
closes https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/475
also needed to fix https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/469
- Added support for Javascript project files in when uploaded from Github
- Give the failing projects a rebuild
> Fix javascript upload support

- Gemfile
- app/views/api/school_owners/_school_owner.json.jbuilder
- app/views/api/school_students/_school_student.json.jbuilder
- app/views/api/school_teachers/_school_teacher.json.jbuilder
- spec/features/class_member/creating_a_batch_of_class_members_spec.rb
- spec/features/class_member/creating_a_class_member_spec.rb
- spec/features/class_member/listing_class_members_spec.rb
- Related to: https://github.com/RaspberryPiFoundation/digital-editor-issues/issues/490
- Ensures a type is defined on each user (this precedes a refactor that's on route to simplify classmember handling)
- Adds a test for owner handling in classmembers
- Adds AP to tests
N/A
> 490: Ensure a type is defined on users, add owner test, fix tests

- app/controllers/api/class_members_controller.rb
- app/views/api/class_members/_class_member.json.jbuilder
- spec/features/class_member/creating_a_batch_of_class_members_spec.rb
- spec/features/class_member/creating_a_class_member_spec.rb
- Fixed ability to add owners to a class
- Fixed owner appearing with teacher icon when first added to a class
> fix owners being added to class

- app/controllers/test_utilities_controller.rb
- lib/tasks/test_seeds.rake
> Debugging statements added for database reseed

- .clabot
> Added Adrian (myself) to CLA bot

- .clabot
Adding Fraser (myself) to cla-bot.
> Add Fraser Speirs (@fspeirs) to .clabot.
